### PR TITLE
Redesigned the website of Soundnode

### PR DESCRIPTION
**Pull request by ghost**
I redesigned the website of Soundnode. Please let me know what you think about it.

Screenshot

### CODE REVIEW

**Comment by weblancaster** [comment]
Hey @wb9688 this is great!

Just a couple of things.. why not just use plain CSS, JS? there is no need to use stylus (if CSS pre-processor use sass), also there is no need to change the entire structure of the project because the only thing you would need is update the HTML, CSS, JS and images.

There is way too much in this PR and I would suggest keep it simple and overwrite what we have without change the project structure.

**Comment by ghost** [comment]
@weblancaster Should I create a new PR with the needed changes or add a new
commit to this PR?

**Comment by weblancaster** [comment]
Now the UI feedback.. 
- Can you remove the waffle icon/link?
- Can the header background be white instead?

**Comment by ghost** [comment]
@weblancaster I would also change that. But, should I create a new PR with
the needed changes or add a new commit to this PR?

**Comment by weblancaster** [comment]
whatever is works for you @wb9688

**Comment by ghost** [comment]
OK, I made a new PR: #7

**Pull request closed without merging**
